name: mon_retraite_app
description: "Application mobile pour les assur√©s retraite - Gan Assurances"
publish_to: 'none'
version: 1.0.0+23

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  provider: ^6.1.2
  fl_chart: ^0.69.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  dash_chat_2: ^0.0.21
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.3.3
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  http: ^1.2.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
